;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables 'nil)
(setq search-ring '("server" "saveh" "|" "$" "dn=" "dev" "make " "[" "[ke" "eval" "scre" "sbo" "elisp" "helm" "push" "BDG"))
(setq regexp-search-ring '("scree"))
(setq kill-ring 'nil)
